<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function wipe_clean_get_services_page_acf_layout_services_intro() {
	return array(
		'key'        => 'layout_wipe_clean_services_intro',
		'name'       => 'services_intro',
		'label'      => 'Первый блок услуг',
		'display'    => 'block',
		'sub_fields' => array(
			array(
				'key'       => 'field_wipe_clean_services_intro_tab_hero',
				'label'     => 'Верхняя часть',
				'name'      => '',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_hero_kicker',
				'label' => 'Небольшой заголовок',
				'name'  => 'hero_kicker',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_hero_title',
				'label' => 'Главный заголовок',
				'name'  => 'hero_title',
				'type'  => 'textarea',
				'rows'  => 3,
			),
			array(
				'key'       => 'field_wipe_clean_services_intro_hero_text',
				'label'     => 'Текст под заголовком',
				'name'      => 'hero_text',
				'type'      => 'textarea',
				'rows'      => 4,
				'new_lines' => 'br',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_hero_primary_action',
				'label' => 'Основная кнопка',
				'name'  => 'hero_primary_action',
				'type'  => 'link',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_hero_secondary_action',
				'label' => 'Вторая кнопка',
				'name'  => 'hero_secondary_action',
				'type'  => 'link',
			),
			array(
				'key'       => 'field_wipe_clean_services_intro_tab_media',
				'label'     => 'Изображения',
				'name'      => '',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'           => 'field_wipe_clean_services_intro_hero_decor_image',
				'label'         => 'Левое декоративное изображение',
				'name'          => 'hero_decor_image',
				'type'          => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'library'       => 'all',
			),
			array(
				'key'           => 'field_wipe_clean_services_intro_hero_cleaner_image',
				'label'         => 'Изображение сотрудницы',
				'name'          => 'hero_cleaner_image',
				'type'          => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'library'       => 'all',
			),
			array(
				'key'           => 'field_wipe_clean_services_intro_hero_interior_image',
				'label'         => 'Изображение интерьера',
				'name'          => 'hero_interior_image',
				'type'          => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'library'       => 'all',
			),
			array(
				'key'       => 'field_wipe_clean_services_intro_tab_overview',
				'label'     => 'Текст ниже',
				'name'      => '',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_overview_title',
				'label' => 'Заголовок нижнего текста',
				'name'  => 'overview_title',
				'type'  => 'textarea',
				'rows'  => 3,
			),
			array(
				'key'       => 'field_wipe_clean_services_intro_overview_summary',
				'label'     => 'Краткий текст',
				'name'      => 'overview_summary',
				'type'      => 'textarea',
				'rows'      => 4,
				'new_lines' => 'br',
			),
			array(
				'key'          => 'field_wipe_clean_services_intro_overview_body',
				'label'        => 'Развернутые абзацы',
				'name'         => 'overview_body',
				'type'         => 'repeater',
				'layout'       => 'row',
				'button_label' => 'Добавить абзац',
				'sub_fields'   => array(
					array(
						'key'       => 'field_wipe_clean_services_intro_overview_body_text',
						'label'     => 'Абзац',
						'name'      => 'text',
						'type'      => 'textarea',
						'rows'      => 4,
						'new_lines' => 'br',
					),
				),
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_overview_more_label',
				'label' => 'Текст кнопки «Ещё»',
				'name'  => 'overview_more_label',
				'type'  => 'text',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_overview_less_label',
				'label' => 'Текст кнопки «Свернуть»',
				'name'  => 'overview_less_label',
				'type'  => 'text',
			),
			array(
				'key'           => 'field_wipe_clean_services_intro_overview_image',
				'label'         => 'Изображение рядом с текстом',
				'name'          => 'overview_image',
				'type'          => 'image',
				'return_format' => 'array',
				'preview_size'  => 'medium',
				'library'       => 'all',
			),
			array(
				'key'       => 'field_wipe_clean_services_intro_tab_cards',
				'label'     => 'Карточки услуг',
				'name'      => '',
				'type'      => 'tab',
				'placement' => 'top',
			),
			array(
				'key'       => 'field_wipe_clean_services_intro_cards_note',
				'label'     => 'Как работают карточки',
				'name'      => '',
				'type'      => 'message',
				'message'   => 'Карточки в слайдере подтягиваются из раздела <strong>Услуги</strong> в админке. Здесь можно менять только нижние кнопки этого блока.',
				'esc_html'  => 0,
				'new_lines' => 'wpautop',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_footer_primary_action',
				'label' => 'Нижняя основная кнопка',
				'name'  => 'footer_primary_action',
				'type'  => 'link',
			),
			array(
				'key'   => 'field_wipe_clean_services_intro_footer_secondary_action',
				'label' => 'Нижняя вторая кнопка',
				'name'  => 'footer_secondary_action',
				'type'  => 'link',
			),
		),
	);
}
