<section class="gallery-preview">
        <div class="_container">
          <div class="gallery-preview__wrapper">
            <div class="gallery-preview__head">
              <h2 class="ui-title gallery-preview__title">Галерея наших работ по уборке квартир, домов и офисов</h2>
            </div>
            <div class="gallery-preview__marquees">
              <div class="gallery-preview__row" data-gallery-marquee-row data-direction="-1" data-speed="36">
                <div class="gallery-preview__track" data-gallery-marquee-track><a class="gallery-preview__item" href="/static/images/section/gallery-preview/gallery-row-1-photo-1.png" data-gallery-item-id="gallery-top-1" aria-label="Уборка кухни крупным планом" data-fancybox="gallery-preview" data-caption="Работа команды ВАЙП–Клин"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-photo-1-500.webp 500w, /static/webp-images/section/gallery-preview/gallery-row-1-photo-1-1000.webp 1000w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-photo-1.png" alt="Уборка кухни крупным планом" loading="lazy" decoding="async" width="1000" height="667" srcset="/static/images/section/gallery-preview/gallery-row-1-photo-1-500.png 500w, /static/images/section/gallery-preview/gallery-row-1-photo-1.png 1000w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item" href="/static/images/section/gallery-preview/gallery-row-1-photo-2.png" data-gallery-item-id="gallery-top-2" aria-label="Влажная уборка дома" data-fancybox="gallery-preview" data-caption="Уборка квартир и домов"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-photo-2-640.webp 640w, /static/webp-images/section/gallery-preview/gallery-row-1-photo-2-1280.webp 1280w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-photo-2.png" alt="Влажная уборка дома" loading="lazy" decoding="async" width="1280" height="720" srcset="/static/images/section/gallery-preview/gallery-row-1-photo-2-640.png 640w, /static/images/section/gallery-preview/gallery-row-1-photo-2.png 1280w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item" href="/static/images/section/gallery-preview/gallery-row-1-photo-3.png" data-gallery-item-id="gallery-top-3" aria-label="Светлая гостиная после клининга" data-fancybox="gallery-preview" data-caption="Результат уборки квартиры"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-photo-3-320.webp 320w, /static/webp-images/section/gallery-preview/gallery-row-1-photo-3-640.webp 640w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-photo-3.png" alt="Светлая гостиная после клининга" loading="lazy" decoding="async" width="640" height="288" srcset="/static/images/section/gallery-preview/gallery-row-1-photo-3-320.png 320w, /static/images/section/gallery-preview/gallery-row-1-photo-3.png 640w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--video" href="/static/images/section/gallery-preview/test-video.mp4" data-gallery-item-id="gallery-top-4" aria-label="Видео процесса уборки" data-fancybox="gallery-preview" data-caption="Видео процесса уборки" data-type="html5video" data-html5video-format="video/mp4" data-width="1280" data-height="720"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-video-poster-960.webp 960w, /static/webp-images/section/gallery-preview/gallery-row-1-video-poster-1920.webp 1920w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-video-poster.png" alt="Видео процесса уборки" loading="lazy" decoding="async" width="1920" height="1225" srcset="/static/images/section/gallery-preview/gallery-row-1-video-poster-960.png 960w, /static/images/section/gallery-preview/gallery-row-1-video-poster.png 1920w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span><span class="gallery-preview__item-badge" aria-hidden="true"><img src="/static/images/section/gallery-preview/gallery-play.svg" alt=""></span></a><a class="gallery-preview__item gallery-preview__item--clone" href="/static/images/section/gallery-preview/gallery-row-1-photo-1.png" data-gallery-item-id="gallery-top-1" aria-label="Уборка кухни крупным планом" data-gallery-clone="" data-gallery-target="gallery-top-1" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-photo-1-500.webp 500w, /static/webp-images/section/gallery-preview/gallery-row-1-photo-1-1000.webp 1000w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-photo-1.png" alt="Уборка кухни крупным планом" loading="lazy" decoding="async" width="1000" height="667" srcset="/static/images/section/gallery-preview/gallery-row-1-photo-1-500.png 500w, /static/images/section/gallery-preview/gallery-row-1-photo-1.png 1000w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--clone" href="/static/images/section/gallery-preview/gallery-row-1-photo-2.png" data-gallery-item-id="gallery-top-2" aria-label="Влажная уборка дома" data-gallery-clone="" data-gallery-target="gallery-top-2" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-photo-2-640.webp 640w, /static/webp-images/section/gallery-preview/gallery-row-1-photo-2-1280.webp 1280w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-photo-2.png" alt="Влажная уборка дома" loading="lazy" decoding="async" width="1280" height="720" srcset="/static/images/section/gallery-preview/gallery-row-1-photo-2-640.png 640w, /static/images/section/gallery-preview/gallery-row-1-photo-2.png 1280w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--clone" href="/static/images/section/gallery-preview/gallery-row-1-photo-3.png" data-gallery-item-id="gallery-top-3" aria-label="Светлая гостиная после клининга" data-gallery-clone="" data-gallery-target="gallery-top-3" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-photo-3-320.webp 320w, /static/webp-images/section/gallery-preview/gallery-row-1-photo-3-640.webp 640w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-photo-3.png" alt="Светлая гостиная после клининга" loading="lazy" decoding="async" width="640" height="288" srcset="/static/images/section/gallery-preview/gallery-row-1-photo-3-320.png 320w, /static/images/section/gallery-preview/gallery-row-1-photo-3.png 640w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--video gallery-preview__item--clone" href="/static/images/section/gallery-preview/test-video.mp4" data-gallery-item-id="gallery-top-4" aria-label="Видео процесса уборки" data-gallery-clone="" data-gallery-target="gallery-top-4" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-1-video-poster-960.webp 960w, /static/webp-images/section/gallery-preview/gallery-row-1-video-poster-1920.webp 1920w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-1-video-poster.png" alt="Видео процесса уборки" loading="lazy" decoding="async" width="1920" height="1225" srcset="/static/images/section/gallery-preview/gallery-row-1-video-poster-960.png 960w, /static/images/section/gallery-preview/gallery-row-1-video-poster.png 1920w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span><span class="gallery-preview__item-badge" aria-hidden="true"><img src="/static/images/section/gallery-preview/gallery-play.svg" alt=""></span></a>
                </div>
              </div>
              <div class="gallery-preview__row gallery-preview__row--reverse" data-gallery-marquee-row data-direction="1" data-speed="38">
                <div class="gallery-preview__track" data-gallery-marquee-track><a class="gallery-preview__item" href="/static/images/section/gallery-preview/gallery-row-2-photo-1.png" data-gallery-item-id="gallery-bottom-1" aria-label="Гостиная после уборки" data-fancybox="gallery-preview" data-caption="Чистый интерьер после клининга"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-photo-1-341.webp 341w, /static/webp-images/section/gallery-preview/gallery-row-2-photo-1-683.webp 683w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-photo-1.png" alt="Гостиная после уборки" loading="lazy" decoding="async" width="683" height="512" srcset="/static/images/section/gallery-preview/gallery-row-2-photo-1-341.png 341w, /static/images/section/gallery-preview/gallery-row-2-photo-1.png 683w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--video" href="/static/images/section/gallery-preview/test-video.mp4" data-gallery-item-id="gallery-bottom-2" aria-label="Видео работы клинеров" data-fancybox="gallery-preview" data-caption="Видео работы команды ВАЙП–Клин" data-type="html5video" data-html5video-format="video/mp4" data-width="1280" data-height="720"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-video-poster-284.webp 284w, /static/webp-images/section/gallery-preview/gallery-row-2-video-poster-568.webp 568w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-video-poster.png" alt="Видео работы клинеров" loading="lazy" decoding="async" width="568" height="388" srcset="/static/images/section/gallery-preview/gallery-row-2-video-poster-284.png 284w, /static/images/section/gallery-preview/gallery-row-2-video-poster.png 568w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span><span class="gallery-preview__item-badge" aria-hidden="true"><img src="/static/images/section/gallery-preview/gallery-play.svg" alt=""></span></a><a class="gallery-preview__item" href="/static/images/section/gallery-preview/gallery-row-2-photo-2.png" data-gallery-item-id="gallery-bottom-3" aria-label="Химчистка мягкой мебели" data-fancybox="gallery-preview" data-caption="Химчистка и глубокая уборка"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-photo-2-1000.webp 1000w, /static/webp-images/section/gallery-preview/gallery-row-2-photo-2-2000.webp 2000w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-photo-2.png" alt="Химчистка мягкой мебели" loading="lazy" decoding="async" width="2000" height="1333" srcset="/static/images/section/gallery-preview/gallery-row-2-photo-2-1000.png 1000w, /static/images/section/gallery-preview/gallery-row-2-photo-2.png 2000w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item" href="/static/images/section/gallery-preview/gallery-row-2-photo-3.png" data-gallery-item-id="gallery-bottom-4" aria-label="Инвентарь для клининга" data-fancybox="gallery-preview" data-caption="Профессиональный инвентарь и безопасная химия"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-photo-3-540.webp 540w, /static/webp-images/section/gallery-preview/gallery-row-2-photo-3-1080.webp 1080w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-photo-3.png" alt="Инвентарь для клининга" loading="lazy" decoding="async" width="1080" height="731" srcset="/static/images/section/gallery-preview/gallery-row-2-photo-3-540.png 540w, /static/images/section/gallery-preview/gallery-row-2-photo-3.png 1080w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--clone" href="/static/images/section/gallery-preview/gallery-row-2-photo-1.png" data-gallery-item-id="gallery-bottom-1" aria-label="Гостиная после уборки" data-gallery-clone="" data-gallery-target="gallery-bottom-1" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-photo-1-341.webp 341w, /static/webp-images/section/gallery-preview/gallery-row-2-photo-1-683.webp 683w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-photo-1.png" alt="Гостиная после уборки" loading="lazy" decoding="async" width="683" height="512" srcset="/static/images/section/gallery-preview/gallery-row-2-photo-1-341.png 341w, /static/images/section/gallery-preview/gallery-row-2-photo-1.png 683w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--video gallery-preview__item--clone" href="/static/images/section/gallery-preview/test-video.mp4" data-gallery-item-id="gallery-bottom-2" aria-label="Видео работы клинеров" data-gallery-clone="" data-gallery-target="gallery-bottom-2" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-video-poster-284.webp 284w, /static/webp-images/section/gallery-preview/gallery-row-2-video-poster-568.webp 568w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-video-poster.png" alt="Видео работы клинеров" loading="lazy" decoding="async" width="568" height="388" srcset="/static/images/section/gallery-preview/gallery-row-2-video-poster-284.png 284w, /static/images/section/gallery-preview/gallery-row-2-video-poster.png 568w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span><span class="gallery-preview__item-badge" aria-hidden="true"><img src="/static/images/section/gallery-preview/gallery-play.svg" alt=""></span></a><a class="gallery-preview__item gallery-preview__item--clone" href="/static/images/section/gallery-preview/gallery-row-2-photo-2.png" data-gallery-item-id="gallery-bottom-3" aria-label="Химчистка мягкой мебели" data-gallery-clone="" data-gallery-target="gallery-bottom-3" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-photo-2-1000.webp 1000w, /static/webp-images/section/gallery-preview/gallery-row-2-photo-2-2000.webp 2000w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-photo-2.png" alt="Химчистка мягкой мебели" loading="lazy" decoding="async" width="2000" height="1333" srcset="/static/images/section/gallery-preview/gallery-row-2-photo-2-1000.png 1000w, /static/images/section/gallery-preview/gallery-row-2-photo-2.png 2000w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a><a class="gallery-preview__item gallery-preview__item--clone" href="/static/images/section/gallery-preview/gallery-row-2-photo-3.png" data-gallery-item-id="gallery-bottom-4" aria-label="Инвентарь для клининга" data-gallery-clone="" data-gallery-target="gallery-bottom-4" aria-hidden="true" tabindex="-1"><span class="gallery-preview__item-media">
                                  <picture>
                                    <source type="image/webp" srcset="/static/webp-images/section/gallery-preview/gallery-row-2-photo-3-540.webp 540w, /static/webp-images/section/gallery-preview/gallery-row-2-photo-3-1080.webp 1080w" sizes="(max-width: 650px) 62vw, 22vw"><img src="/static/images/section/gallery-preview/gallery-row-2-photo-3.png" alt="Инвентарь для клининга" loading="lazy" decoding="async" width="1080" height="731" srcset="/static/images/section/gallery-preview/gallery-row-2-photo-3-540.png 540w, /static/images/section/gallery-preview/gallery-row-2-photo-3.png 1080w" sizes="(max-width: 650px) 62vw, 22vw">
                                  </picture></span></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
